services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: ./CustomerCrudApi
      dockerfile: Dockerfile
    container_name: CustomerCrudApi
    ports:
      - "5028:5028"
    depends_on:
      - mongodb
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      MongoDB__ConnectionString: "mongodb://mongodb:27017/customerDb"

  frontend:
    build:
      context: ./CustomerApp
      dockerfile: Dockerfile
    container_name: CustomerApp
    ports:
      - "4200:4200"
    depends_on:
      - backend
    command: ["ng", "serve", "--host", "0.0.0.0"]
volumes:
  mongo-data:
